apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/giladsh1/applicationset.git
        revision: dev
        files:
          - path: apps/dev/apps/appsList.json
        requeueAfterSeconds: 30
  template:
    metadata:
      name: "{{name}}-dev"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/giladsh1/applicationset.git
        targetRevision: v.1.0.0
        path: charts/apps
        helm:
          valueFiles:
            - ../../values-environments/dev/common.yaml
            - ../../values-apps/{{name}}/common.yaml
            - ../../values-apps/{{name}}/dev.yaml
            - ../../versions/dev/{{name}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=true
          - CreateNamespace=false
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
