apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/giladsh1/applicationset.git
    path: charts/infra
    targetRevision: dev
    helm:
      releaseName: infra
      valueFiles:
        - values-environments/dev/common.yaml
        - values-apps/infra/common.yaml
        - values-apps/infra/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
