apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-apps
spec:
  generators:
  - git:
      repoURL: https://github.com/giladsh1/applicationset.git
      revision: HEAD
      files:
        - path: app-lists/dev-app-list.json
  template:
    metadata:
      name: '{{name}}-dev'
    spec:
      project: default
      source:
        repoURL: https://github.com/giladsh1/applicationset.git
        targetRevision: HEAD
        path: charts/app
        helm:
          valueFiles:
            - values/{{name}}/common.yaml
            - values/{{name}}/dev.yaml
            - versions/dev/{{name}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - CreateNamespace=false
          - PrunePropagationPolicy=foreground
          - PruneLast=false
