{{- if .Values.ingress.enabled -}}
{{- $fullName := include "application.fullname" . -}}
{{- $appLables := include "application.labels" . }}
{{- range $rule := .Values.ingress.rules }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $fullName }}-{{ $rule.name }}"
  labels:
    {{- $appLables | nindent 4 }}
  {{- with $rule.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $rule.className }}
  {{- if $rule.tls }}
  tls:
    {{- range $rule.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $rule.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .backend.service.name }}
                port:
                  {{- if .backend.service.port.number }}
                  number: {{ .backend.service.port.number }}
                  {{- else if .backend.service.port.name }}
                  name: {{ .backend.service.port.name }}
                  {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
