{{- if and .Values.deployment.enabled .Values.deployment.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  {{- if .Values.deployment.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.deployment.podDisruptionBudget.minAvailable }}
  {{- else if .Values.deployment.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.deployment.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
{{- end }}
