{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "application.serviceAccountName" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- include "application.serviceaccountAnnotations" . | indent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}